// Channel
export const FETCH_CHANNEL_REQUEST = 'FETCH_CHANNEL_REQUEST';
export const FETCH_CHANNEL_SUCCESS = 'FETCH_CHANNEL_SUCCESS';
export const FETCH_CHANNEL_FAILURE = 'FETCH_CHANNEL_FAILURE';

export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAILURE = 'SEND_MESSAGE_FAILURE';

export const START_TYPING = 'START_TYPING';
export const STOP_TYPING = 'STOP_TYPING';

export const CLEAR_CHANNEL = 'CLEAR_CHANNEL';
