// Channel
export const FETCH_CHANNEL_REQUEST = 'FETCH_CHANNEL_REQUEST';
export const FETCH_CHANNEL_SUCCESS = 'FETCH_CHANNEL_SUCCESS';
export const FETCH_CHANNEL_FAILURE = 'FETCH_CHANNEL_FAILURE';

export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAILURE = 'SEND_MESSAGE_FAILURE';

export const ADD_TYPIST = 'ADD_TYPIST';
export const REMOVE_TYPIST = 'REMOVE_TYPIST';
export const CLEAR_TYPISTS = 'CLEAR_TYPISTS';

export const CLEAR_CHANNEL = 'CLEAR_CHANNEL';
